# Tedicross Bot, bridging Telegram and Discord
# 1. Setup as per the README.
# 2. Start with:
#     docker compose up --detach
#
# Public Settings are in `./data/settings.yaml`.
# Secrets ought to be in the `.env` file.

services:
    tedicross:
        # https://hub.docker.com/r/tedicross/tedicross/tags
        image: tedicross/tedicross:v0.12.4
        container_name: tedicross
        restart: unless-stopped
        env_file:
        - .env
        volumes:
        - ./data:/opt/TediCross/data
